### ISSUE TITLE
[Proposal] Allow importing properties definitions from other components

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface#119]
Initial discussion started in https://github.com/msaraiva/surface/pull/117.

## Questions

  - Should we also be able to import `data` and `context` assigns?
    - If so, we need to find a more suitable name than `import_props` or `props`. It could be something generic like `include` or something specific for each type like `import_props`, `import_context_sets`, etc.
  - Should we allow selective imports? For instance, using `only` and `except` (similar to Elixir's built-in import).

## Proposal

Add an `include` function to the API that allows importing properties (and maybe context assigns) from other components.

### Example without options

```elixir
defmodule Field do
  property label, :string
  property value, :string
  ...
end

defmodule EnhancedButton do
  include Button
  ...
end
```

Usage:

```jsx
<EnhancedButton label="some label" />
```
### Example with  options

```elixir
defmodule CustomPanel do
  use Surface.Component

  include AlphaPanel, into: :alpha_props, prefix: :alpha
  include BetaPanel, into: :beta_props, prefix: :beta

  def render(assigns) do
    <AlphaPanel :props={{ @alpha_props }}>
    ...
    </AlphaPanel>
    <BetaPanel :props={{ @beta_props }}>
    ...
    </BetaPanel>
  end
end
```

Usage:

```jsx
<CustomPanel 
  alpha_label="label for AlphaPanel" 
  alpha_hidden=false
  beta_label="label for BetaPanel"
  beta_hidden=true
/>
```

**Comment by msaraiva** [comment]
We could start importing only properties for `v0.1.0` and then investigate later if it's worth it to support contexts, etc.

**Comment by msaraiva** [comment]
It looks like this is not as useful as we thought it would be. It seems using some metaprogramming solves most of the cases people have, so I'm closing it until we get more requests of this kind.

**Comment by Zurga** [comment]
I do like the idea of this, because it does not put pressure on the project developing the components that would be included in other projects. Also, an improvement could be that the including component can choose which props to import.

Currently, I am continuing work to implement Form components for SurfaceBulma and copy-pasting the props from Surface.Form makes my hair stand up.

For SurfaceFontAwesome I used metaprogramming to achieve what I want to do with the Form component, but that was my project, so I only gave myself extra work. I don't want to have to ask Surface to also do that work.

@msaraiva, could you give an indication to the amount of effort that is needed to get this to the point where props can be imported?

**Comment by Zurga** [comment]
I have figured out a basic working version, would you consider a pull request for this functionality?

**Comment by msaraiva** [comment]
Hi @Zurga!

We're considering bringing back this discussion as we want to have a way to define some kind of "interface"  that we could reuse to automatically import props/slots from it and also help us to support some compile-time checks for upcoming dynamic components based on those interfaces. In case you already have some ideas on that regard, feel free to share here. I'll open a new issue soon summarizing all we have discussed so far.
