### ISSUE TITLE
Improving types support

### ISSUE THREAD

**Issue by paulstatezny** [surface-ui/surface#162]
First of all, thanks for Surface!

The docs currently say:

> **Note:** Currently, some of the types above work just as annotations and don't have any practical use aside from documentation. If the type you need is not in that list, you can safely use `:any` instead. However, some other types like `:css_class`, `:list` and `:event` are handled differently, i.e. there are extra rules and behaviours applied to them.

Is there a technical or design reason to not validate property types? Could Surface (for example) emit a warning if you supply an invalid type to a component? Or maybe have a "strict mode" config option where it crashes if you supply the wrong type?

I'm not sure if this is technically unrelated, but I would _love_ to be able to supply `values: [:foo, :bar]` and have Surface somehow yell at me if I pass in something other than `:foo` or `:bar`. 🙂

**Comment by msaraiva** [comment]
Hi @paulstatezny!

> Is there a technical or design reason to not validate property types? Could Surface (for example) emit a warning if you supply an invalid type to a component? Or maybe have a "strict mode" config option where it crashes if you supply the wrong type?

We recently added the ability to do some validation at compile-time. Some of them are already validated. However, since Elixir is a dynamic language, there are many cases where there's nothing we can do. Here are some examples of types we can validate at compile-time:

  * The passed value is a literal - See `atom`'s [literal_to_ast_node/4](https://github.com/msaraiva/surface/blob/f1c75f92513b607c98ba578030a647e0f5d6d11c/lib/surface/type_handler/atom.ex#L6-L13).
  * The passed expression can be recognized as the expected type - See `explict_keyword`'s [expr_to_quoted/6](https://github.com/msaraiva/surface/blob/f1c75f92513b607c98ba578030a647e0f5d6d11c/lib/surface/type_handler/explict_keyword.ex#L11-L19).

Any other kind of expression passed can only be validated at runtime. See `styles`'s [expr_to_value/2](https://github.com/msaraiva/surface/blob/f1c75f92513b607c98ba578030a647e0f5d6d11c/lib/surface/type_handler/style.ex#L17-L31).

We've added compile-time validation to some of the types but most of them currently have only runtime validation. PRs are welcome :) 

There are other interesting cases that we could start validating at compile-time, e.g. the passed expression is a declared assign, e.g. `@some_assign`. In this case, we could introspect the component's metadata to retrieve the type of the assign and check if it's compatible with the property's type. We could even try to treat a few other simple expressions but the more we go in this direction, the more complex it will get to maintain all different types.

> I'm not sure if this is technically unrelated, but I would _love_ to be able to supply `values: [:foo, :bar]` and have Surface somehow yell at me if I pass in something other than `:foo` or `:bar`.

That's possible for two of the cases already mentioned:

  1. the value passed is a literal 
  2. the value passed is an assign

Our plan is to add as much compile-time validation as possible and checking `values` is certainly one of the planned features. In case you want to give it a try and submit a PR, please let me know. I'd be glad to give you any assistance you might need ;)

**Comment by capitalist** [comment]
I wonder if there's a path to do something like have a `prop` accept a `norm` schema and, if provided, validate it at runtime.

I totally understand this wouldn't be a core feature of surface so surface would need the integration hooks.

**Comment by msaraiva** [comment]
> I wonder if there's a path to do something like have a `prop` accept a norm schema and, if provided, validate it at runtime.

I confess I don't like to have to reimplement things like type validations and other stuff like we currently do in Surface. I wish we had an "official" solution for that. Unfortunately, we don't. Typespects are far from ideal and mostly used for documentation and/or dialyzer. There are a bunch of libs that try to bring some sanity to Elixir on that regard but most of them are usually incomplete and unmaintained. Choosing any of them as a hard dependency can be potentially risky. 

Having said that, I like `norm` a lot. It's very well maintained by Chris Keathley, who's certainly one of the best Elixir wizards out there. I believe this should be part of a broader discussion regarding "types" in general and how we should implement them in Surface. As far as I can remember, @lnr0626 had an idea of allowing custom types similar to what `ecto` does.

Since declaring typed `props` and `data` are at the heart of Surface, we need to take a very responsible decision so I'll leave this open so we can keep discussing until we find a feasible and safe solution.

**Comment by lnr0626** [comment]
At a high level, my idea was to have `prop` accept a module that conformed to the `TypeHandler` behavior, and use the current atoms as shorthand for their corresponding `TypeHandler`s. This would allow us to (for instance) remove `context_get` and `context_put` from the list of 'official types', as they're fairly specific to the `Context` component. This would also allow users to define their own types.

`norm` looks really cool -  I'll have to take a deeper look into it. It could be a powerful addition to the `TypeHandler` modules to allow them to specify their schemas. I have to differ to @msaraiva on the risk of adding it as a dependency though - I don't have a good understanding of the landscape of these types of libraries currently

One challenging thing would be the divide between what we can validate at compile time vs. at runtime. It'd be entirely possible to add validation to things which were defined at compile time (i.e. if you pass an assign, that assign is of a compatible type, or if you pass a literal that literal is of the right form); however, there's a very large class of things where that either could still lead to issues or just wouldn't work. For instance, while the assign might technically be of the right type, if we can't do any validation that assign is actually of that type, we'd give the user a false sense of confidence. All that means is that our validation would have to have some runtime component to be complete.

I'm very much on board with adding more and better validation capabilities to props/data, though as @msaraiva said any decision is going to have fairly far reaching consequences.

**Comment by msaraiva** [comment]
This is new but looks promising https://hexdocs.pm/mavis/Type.html.

Maybe we should keep it in our radar.

**Comment by olivermt** [comment]
My $0.02 on this topic is:

Types are not first class in Elixir, and there are no known (at least that I know of?) plans to make them first class.
If you want types, you can use Gleam or other derivatives on the BEAM.

I suggest a very pragmatic approach:
This auto valiates by simply doing foo in values:
`prop foo, :string, values: ~w(foo bar baz)`

Do you want something more advanced?
`prop foo, :map, validator: &my_nice_foo_validator/1`
or
`prop foo, :map, validator: &my_nice_foo_validator/2`

/1 gets just the prop value
/2 gets prop value and assigns (you often want to validate in context of the rest of the assigns)

How this will work in a runtime, thats up to the smarter people to solve :D

**Comment by msaraiva** [comment]
I'm closing it since there's no plan to move forward on this one for now. We can reopen later when we feel it's time to bring back the discussion.
