### ISSUE TITLE
Replace <template> and <slot> with <Template> and <Slot> to avoid conflicts

### ISSUE THREAD

**Issue by lnr0626** [surface-ui/surface#259]
This is related to what i mentioned in https://github.com/msaraiva/surface/issues/107#issuecomment-741912493

I recently found the need for an actual `<template>...</template>` node for one of my hooks, and had to do:
```
<#Raw><template></#Raw>
...
<#Raw></template></#Raw>
```

while this does work, it's not ideal - should we switch from `<template>` and `<slot>` nodes to `<Template>` and `<Slot>` components (with some time supporting both to make it a bit easier to do the switch over)? Or is there another way to allow template nodes that are treated as standard html template elements?

**Comment by msaraiva** [comment]
I think we should switch to `<Template>` and `<Slot>` as soon as possible since we've seen more and more people facing this issue, like is was mentioned here https://elixirforum.com/t/surface-a-component-based-library-for-phoenix-liveview/27671/84. Maybe we don't even need to implement them as independent components for now and just keep the current hardcoded implementation.

> with some time supporting both to make it a bit easier to do the switch over

I don't think we should worry about it. If people are using `<#Raw><template>` to overcome that, it should be straightforward to replace it after we release a new version.

**Comment by lnr0626** [comment]
> Maybe we don't even need to implement them as independent components for now and just keep the current hardcoded implementation.

+1 to that

regarding making it easier to switch, i was more referring to switching from `<template>` and `<slot>` to `<Template>` and `<Slot>` - i.e. release a new patch version that has support for both, then in the next minor remove support for `<template>` and `<slot>` (supporting both for a short time should be trivial if we're keeping the current hard coded implementation, and can log a warning when we encounter the lower cased version)

**Comment by msaraiva** [comment]
> supporting both for a short time should be trivial if we're keeping the current hard coded implementation, and can log a warning when we encounter the lower cased version

On. I see. That sounds perfect indeed!

**Comment by msaraiva** [comment]
Closing this in favour of https://github.com/surface-ui/surface/issues/340.
