### ISSUE TITLE
Add :pid as a valid type

### ISSUE THREAD

**Issue by colinsmetz** [surface-ui/surface#280]
I recently made a project where at some point I needed to store a PID as `data`. However, I was surprised to see that the `:pid` type didn't exist, so I had to use `:any`.

Would it make sense to add `:pid` to the list of valid types?

**Comment by Malian** [comment]
Thanks @colinsmetz for highlighting this.

I was also surprised to not see `:struct` as a valid type but `:changeset`. Of course, in this case, we can use `:map`, but it feels more natural from my point of view to use `:struct`.

I listed additional types we could add to the API:

- `:pid`
- `:struct`
- `:tuple`
- `:port`
- `:reference`

We could also combine some of them:
- `:identifier` = pid, port, reference

@miguel-s @msaraiva @lnr0626 what's your opinion about adding these types in the API?

**Comment by lnr0626** [comment]
at this point those types would all behave the same as `:any` and so would only really serve as additional documentation of the expected type.

I definitely think `:tuple` would make sense, and probably `:struct` as well; but i'm not sure about `:pid`, `:port`, `:reference`, or `:identifier` - on one side because there wouldn't be any validation of what's passed in for these types<sup>1</sup>, and so it could give a false sense of security; on the other hand it allows more clearly expressing intent than `:any` or `:map` and we already have a few things that are in a similar vein (`:date`, `:datetime`, `:changeset`, `:number`, `:fun`, etc.). 

this also ties into the discussion in #162

<sup>1</sup> Most of the types that we explicitly support do have special parsing or handling (i.e. for literals)

**Comment by msaraiva** [comment]
Since we haven't decided yet which direction we should take regarding https://github.com/msaraiva/surface/issues/162, I believe we'll have to keep adding types that will serve just as doc/annotation like those suggested.

> Most of the types that we explicitly support do have special parsing or handling (i.e. for literals)

Now they also may have special treatment in the Catalogue, e.g. editing/validating props from user input.

**Comment by lnr0626** [comment]
> Now they also may have special treatment in the Catalogue, e.g. editing/validating props from user input. It may be worth it to mention that in the docs.

good point, i hadn't checked out the catalogue's type handling

**Comment by miguel-s** [comment]
Having prop types as documentation has been very useful for me (prevented mistakes and saved time), even when they aren't checked. And any time I have to use `:any` or use `:map` for a struct it feels like I'm doing something wrong.
Having more types to choose from would be positive from my view (sometime even union types :))

**Comment by msaraiva** [comment]
> Having more types to choose from would be positive from my view (sometime even union types :))

Fair enough. So do you think we should take the opportunity and add all missing [basic](https://hexdocs.pm/elixir/typespecs.html#basic-types) and [built-in](https://hexdocs.pm/elixir/typespecs.html#built-in-types) types?

Regarding union types, it would be cool to have them but I'm afraid we need to wait for a decision on https://github.com/msaraiva/surface/issues/162 :)

**Comment by Malian** [comment]
We must surely add `:struct` and `:tuple` and maybe the basic ones. I am not sure about the built-in types. For example, I find it strange to add the following types:
- none
- no_return
- timeout

**Comment by msaraiva** [comment]
@Malian I agree. It makes no sense to add those types.

**Comment by Malian** [comment]
@colinsmetz some new types have been added into `master`, feel free to update your code base with the `:pid` type :wink:
