### ISSUE TITLE
Include a wrapper for `live_file_input`, and possibly API for allowing uploads via prop/data macro

### ISSUE THREAD

**Issue by harmon25** [surface-ui/surface#298]
Surface currently includes a `FileInput` wrapper component for the phoenix `file_input` html helper. It would be nice if Surface also included a wrapper for the LiveView `live_file_input` html helper.

Here is a small prototype that should work.

```elixir
defmodule LiveFileInput do
  use Surface.Component
  @doc "Upload specified via `allow_upload`"
  prop upload, :any, required: true
  @doc "Classes to be used on the generated `input` element"
  prop class, :css_class, default: []
  @doc "Other DOM attributes to be passed to the `input` element" 
  prop opts, :keyword, default: []
   
  def render(assigns) do
    ~H"{{ live_file_input(@upload, [class: @class] ++ @opts) }}"
  end
end
```

Usage: 
(assumes `allow_upload` has been called in parent lv or live_component, with the `:component` key)
```elixir
~H"""
<LiveFileInput upload={{ @uploads.component }}  />
"""
```

Also curious if there might be room for a special `data` or `prop` API that would be able to take care of allowing uploads:
```elixir
socket = allow_upload(socket, :component, accept: ~w(.json), max_entries: 1)
```

Concept:
```elixir
prop, :file, :upload, accept: ~w(.json), max: 1

#AND/OR

data, :file, :upload, accept: ~w(.json), max: 1
```
Thoughts?

**Comment by miguel-s** [comment]
The prototype looks good to me! Do you want to go ahead and open a PR?

We can explore the prop/data concept separately.

**Comment by msaraiva** [comment]
Hi @harmon25!

> Also curious if there might be room for a special `data` or `prop` API that would be able to take care of allowing uploads:

Yes. There's certainly room for that! If we create a new type `:upload` and allow:

```elixir
data avatar, :upload, accept: ~w(.json), max_entries: 1
```

we could call `allow_upload` automatically so you wouldn't have to implement `mount`. Then you could just:

```jsx
<Form>
  ...
  <LiveFileInput upload={{ @avatar }}/>
</Form>

```

**Comment by Malian** [comment]
@harmon25 & @msaraiva please find a first implementation of an `:upload` type for `data` here #311

**Comment by msaraiva** [comment]
@harmon25 do we want to change the API to accept:

```jsx
<LiveFileInput upload={{ @avatar }}/>
```

instead of:

```jsx
<LiveFileInput upload={{ @uploads.avatar }}/>
```
?

It seems to make sense since whenever we define a `data` as in:

```elixir
data avatar, :upload, accept: ~w(.json), max_entries: 1
```

we're automatically defining an assign `@avatar`, however, I believe that assign will not be updated whenever `@uploads` changes, for instance, when the progress changes. Does the `update` callback gets called when the progress change? If so, we can use it to update our assigns automatically in the PR @Malian is working, otherwise, we'll have to stick with `@uploads.avatar`, which might be a bit confusing.

**Comment by Malian** [comment]
>however, I believe that assign will not be updated whenever `@uploads` changes, for instance, when the progress changes. Does the `update` callback gets called when the progress change? If so, we can use it to update our assigns automatically in the PR @Malian is working, otherwise, we'll have to stick with `@uploads.avatar`, which might be a bit confusing.

The update callback is not called when the progress change. After a few test, we are not able to use the short syntax `@avatar` as it is not updated. I'll try to understand how the javascript part works.

**Comment by msaraiva** [comment]
Ok. In this case, we have three options:

### Option 1
Create a type handler for `:upload` which can internally convert `@avatar` into `@uploads.avatar`. This would work but only when passing the value as property like in:

```
<LiveFileInput upload={{ @avatar }}/>
```
not for direct access like:

```
<!-- This would not be responsive -->
<For each={{ entry <- @avatar.entries }}>
   ...
</For>
```

so we'd have to provide a component to replace the `for` if we want to be consistent (using the assign directly instead of through `@uploads`). Something like:

```
<Entries upload={{ @avatar }} :let={{ entry: entry }}>
...
</Entries>
```

### Option 2

We forget about defining individual uploads as data and allow defining the `uploads` data and pass the configs as an option. Example:

```elxir
data uploads, :uploads, config: [
  avatar: [accept: ~w(.json), max_entries: 1],
  icon: [accept: ~w(.png), max_entries: 2],
  ...
]
```

One weird thing about this one is that the user will not be able to create arbitrary data of type `:uploads`. Only one can be defined and the name must be `uploads`.

### Option 3

We just create the wrappers and don't call `allow_upload` automatically. Leaving this job to the user as in a vanilla LV project.

**Comment by Malian** [comment]
@msaraiva & @harmon25 I deep dive in Phoenix Live view code and I do not have good news.

Special events, like `progress` and  `drop_uploaded_entries` are consumed by the `Phoenix.LiveView.Channel` module and it updates the socket with the new `@uploads` assign. I am suspecting that other special event are consumed in this module.

The `handle_info(:progress, ...)` function has a callback to a function we can define in the `progress` option.

https://github.com/phoenixframework/phoenix_live_view/blob/c4225357b28972fecb95f0742f9d41af13e7dad6/lib/phoenix_live_view/channel.ex#L133-L151

Unfortunatly, `drop_uploaded_entries` does not have that kind of callback.

I forked the [live_upload_example from mcrumm](https://github.com/mcrumm/live_upload_example) and adapt it to Surface to show what I had to implement to be able to manage the `@avatar` annotation. Everything does not work :cry:  You can find it on my  github account in the Surface branch: https://github.com/Malian/live_upload_example/tree/surface

> Option 1
> not for direct access like:
> 
> 
> <For each={{ entry <- @avatar.entries }}>
>    ...
> </For>
> 
> so we'd have to provide a component to replace the for if we want to be consistent (using the assign directly instead of through @uploads). Something like:
> 
> <Entries upload={{ @avatar }} :let={{ entry: entry }}>
> ...
> </Entries>

If we are not able to perform a simple for loop, I am not in favour of this solution as it includes a new component and, I believe, reduce clarity in the code. It is not clear that `<Entries>` is a loop over entries in `@avatar`. Too much cognitive overhead

I prefer the Option 2 over the Option 3 as we handle everything for the developer. With the option 3 I have the feeling we do half of the job and the developer will 90% receives a warning or a CompilationError because he had not allow upload in the mount function. I have a suggestion for an Option 4 which may not be much appreciated :grin: 

### Option 4

We create a new macro `upload` that abstract the `data :uploads, :upload, config: [...]` and we still use the `@uploads` assigns.

```
upload avatar, accept: :any, max_entries: 3, progress: &handle_progress/3
```

What I like in this solution is that the intention is clear, we do not let the user think he can create a data `data :my_uploads, :upload, ...`.

From my point of view, using `@uploads.avatar` didn't bother me as it's what the developer will find in the Phoenix Live View documentation, and I believe it will reduce the cognitive overhead for users that start with Surface. After a night's sleep I see this as an advantage!

What I do not like with the current implementation with `data` is that we will confuse the user as we create an underlying @avatar assign that could be used, but that would not be updated... It will result in issue and questions from developers on the forum and on github. Just because of that, I am in favour to change the current implementation with something more explicit: option 2 or option 4.

WDYT?

**Comment by miguel-s** [comment]
Purely form a user's perspective I really like option 4!

This macro could also be used multiple times, right? Something like:
```
upload avatar, accept: :any, max_entries: 1, progress: &handle_progress/3
upload icon, accept: ~w(.png), max_entries: 3, progress: &handle_progress/3
```

**Comment by Malian** [comment]
@miguel-s 
> Purely form a user's perspective I really like option 4!
> 
> This macro could also be used multiple times, right? Something like:
> 
> ```
> upload avatar, accept: :any, max_entries: 1, progress: &handle_progress/3
> upload icon, accept: ~w(.png), max_entries: 3, progress: &handle_progress/3
> ```

Yes. If you would like to test it you just have to modify my current PR by adding this codes in the right places:
```elixir
  # api.ex
  arities: = %{
    ...,
    upload: [1, 2]
  }

  defmacro upload(name_ast, opts_ast \\ []) do
    build_assign_ast(:data, name_ast, :upload, opts_ast, __CALLER__)
  end

  # live_component.ex
  use Surface.API, include: [:prop, :slot, :data, :upload]

  # live_view.ex
  use Surface.API, include: [:prop, :data, :upload]
```
It's probably not the final implementation, it is just for testing purpose but as everything is already implemented it's easier to get an idea :)

**Comment by harmon25** [comment]
Yea Option 4 looks good! 👍 

Uploads are complex enough it seems, which warrants its own macro, with more accompanying documentation than something like a `:string` type requires.  

An `:upload` type also could not be used as a `prop` type and only works in the two (live_view, and live_component) contexts - which is a bit ambiguous...

The macro can be both documented to only work in live_views and live_components, and maybe include some compile time error that indicates it needs to be declared in either a `Surface.LiveView or Surface.LiveComponent` if possible.

**Comment by msaraiva** [comment]
> From my point of view, using @uploads.avatar didn't bother me as it's what the developer will find in the Phoenix Live View documentation, and I believe it will reduce the cognitive overhead for users that start with Surface. After a night's sleep I see this as an advantage!

Agreed. We should always try to keep the API as close as possible to LV.

I like option `#4` and although I want to avoid as much as possible adding new macros to the API, I think this one may be worth it. Let's go for it!

**Comment by msaraiva** [comment]
Closing this as #307 has been merged and the `update` macro is being discussed in #311.
