### ISSUE TITLE
Form.Submit cannot contain custom components

### ISSUE THREAD

**Issue by PatrickSachs** [surface-ui/surface#342]
Hello there,

I am currently trying out surface. Rather enjoying the experience so far, although it takes a bit to shift my mental model from the SPA world I am used to :)

I am running into an issue that the Form.Submit button cannot contain custom components in its label:
```elixir
<Surface.Components.Form.Submit class="bg-sahnee-pink-500 rounded hover:bg-sahnee-pink-400 p-2 text-white">
  <Components.Icon icon="mdi-content-save" />
  Save
</Surface.Components.Form.Submit>
```
I'd assume that this is due to it being passed down to Phoenix which then in turn actually renders it. (Which uses the content_tag function that apparently can not contain custom components)

```
** (exit) an exception was raised:
    ** (ArgumentError) cannot convert component Sahnee.Business.Web.Components.Icon with id nil to HTML.

A component must always be returned directly as part of a LiveView template.

For example, this is not allowed:

    <%= content_tag :div do %>
      <%= live_component @socket, SomeComponent %>
    <% end %>
```

Is there any workaround or can this be fixed on the Surface side? I was considering ditching the form wrappers altogether anyways later on, but am wary of doing so since I suspect that would also make me loose out of the built in security features like CSRF.

Thank you for your time and the great library!

**Comment by msaraiva** [comment]
Hi @PatrickSachs!

Assuming the underlying `submit/2` function provided by phoenix just creates a `<button type="submit">...</button>`, I believe you could use Surface's own `<Button>` component, which is `content_tag` free. Something like this should work:

```jsx
<Button opts={{ type: "submit" }} ...>
  ...
</Button>
```

@miguel-s do you think we should reimplement `<Submit>` wrapping our `<Button>` instead of `submit/2`? Or maybe phoenix's implementation does something extra? Also, would a `type` prop be welcome in `<Button>`?

**Comment by miguel-s** [comment]
@msaraiva just double checked Phoenix's `submit/2` and seems to be pretty straighforward to reimplement our own version, let's go for it.

We might also want to rename the `<Button>` component to something closer to what it actually does.
The current name implies that this component builds a generic button, but actually it's based on Phoenix's `button/2`, which builds a very specialized button for submitting data to the server.

This is what the [docs](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#button/2) say:
> Generates a button that uses a regular HTML form to submit to the given URL.
Useful to ensure that links that change data are not triggered by search engines and other spidering software.

@PatrickSachs in the meanwhile you should be ok using a regular html submit button `<button type="submit" class="...">...</button>`

**Comment by PatrickSachs** [comment]
Thanks for the reply! I've gone ahead and done that.

This is probably a second issue, but while doing that I've ran into a separate issue: I've gone ahead and created my own button component that applies the correct classes, etc.

```elixir
defmodule MyProjectWeb.Components.Button do
  use MyProjectWeb, :component

  slot default

  def render(assigns) do
    ~H"""
    <button class="bg-sahnee-pink-500 text-white rounded p-2 text-xs">
      <slot />
    </button>
    """
  end
end
```

This works well, however I'm really missing features like event/attribute forwarding. Since now I'd like to use this button this way:

```elixir
<Components.Button :on-click="user_detail" phx-value-user={{user.id}}>
  <Components.Icon icon="mdi-content-save" />
  Inspect user
</Components.Button>
```

Which doesn't work since I have not declared `:on-click` and `phx-value-user` on my button as props. 

I'd love to see a feature that would allow me for "forward" undeclared props to another component (e.g. `<button class="…" @forward>` - would probably have to work differently to support static analysis by IDEs).

Since I don't want to declare every possible event/event value before hand, which would also have to use a different syntax as well. I've already done so in the past with `class` and `style` attributes on some other components, but I feel like such a feature would be more elegant and expressive (+ frameworks like Vue 2 also support this, they inherit undeclared props to the root DOM node)

**Comment by PatrickSachs** [comment]
Just looked through the issues, I guess this essential is #340?

**Comment by miguel-s** [comment]
@PatrickSachs big improvements coming, stay tuned :)

But you can already do somthing like that using the `:attrs` directive in your `<Button>` component, check out #344 to see an example with the new `<Submit>` component. If you have any questions drop by the Surface Slack channel.

PR is merged, so closing this issue.

**Comment by paulstatezny** [comment]
> We might also want to rename the <Button> component to something closer to what it actually does.
The current name implies that this component builds a generic button, but actually it's based on Phoenix's button/2, which builds a very specialized button for submitting data to the server.

@miguel-s Personally I think it's a feature (not a bug!) that these core Surface components merely wrap Phoenix.HTML's core functionality.

Surface adds an extra layer of abstraction that you must understand in order to "get stuff done".￼￼ In the development shop where I work I'm training people who are completely fresh to Phoenix, LiveView, *and* Surface. It's really useful to say, "this component is just a wrapper around Phoenix.HTML.Form.submit/3" or whatever it is. So if you understand that, you're 90% of the way to understanding this.
