### ISSUE TITLE
Adding submit="" and change="" to form results in duplicate phx-target on the form element

### ISSUE THREAD

**Issue by joshuataylor** [surface-ui/surface#407]
Minor bug, when doing something like this:
```
<Form for={{ @form }} submit="save" change="change">
```

results in double `phx-target="1"` on the form. Having just submit OR change shows a single `phx-target="1"`.

**Comment by miguel-s** [comment]
@joshuataylor thanks for opening the issue!

Apart from the extra clutter in the HTML, does this cause any other problems?

**Comment by joshuataylor** [comment]
Not that I know if, not sure if this would cause problems?

**Comment by msaraiva** [comment]
That's the expected behaviour and shouldn't bring any problem unless you try to set a different target for each event. Due to a LV limitation, that's not possible yet. If that's that case, LV would receive only one of them (I believe the last one) rendered.  

@miguel-s one thing we should consider is to check the values at run-time. If it's duplicated, we could remove one of them, if they are different, we could emit a proper warning pointing the LV issue.
