### ISSUE TITLE
Boolean attributes not handled correctly

### ISSUE THREAD

**Issue by kernel-io** [surface-ui/surface#411]
I have some buttons that I'd like to disable based on changeset being invalid etc, currently this is more difficult than it should be while using Surface components (such as the inbuilt `<Submit>` button), passing a boolean value for the disabled attribute doesn't work as the HTML spec requires, and also not as it works in Phoenix.

https://hexdocs.pm/phoenix_html/Phoenix.HTML.Tag.html#tag/1-boolean-values

I made a change to `opts_to_attrs` in the `utils.ex` file, but it doesn't seem to update  when the state changes, I most likely have done it in the wrong place, and `opts_to_attrs` is a one time thing only.

Below is my modified `opts_to_attrs/1`

```
def opts_to_attrs(opts) do
    for {key, value} <- opts do
      case {key, value} do
        {:phx_capture_click, _} -> {:"phx-capture-click", value}
        {:phx_click, _} -> {:"phx-click", value}
        {:phx_window_focus, _} -> {:"phx-window-focus", value}
        {:phx_window_blur, _} -> {:"phx-window-blur", value}
        {:phx_focus, _} -> {:"phx-focus", value}
        {:phx_blur, _} -> {:"phx-blur", value}
        {:phx_window_keyup, _} -> {:"phx-window-keyup", value}
        {:phx_window_keydown, _} -> {:"phx-window-keydown", value}
        {:phx_keyup, _} -> {:"phx-keyup", value}
        {:phx_keydown, _} -> {:"phx-keydown", value}
        {:phx_target, _} -> {:"phx-target", value}
        {:data, _} -> data_to_attrs(value)
        {_, true} -> {:"#{key}", key}
        {_, false} -> nil
        _ -> {key, value}
      end
    end
    |> List.flatten()
    |> Enum.reject(&is_nil/1)
  end
```

**Comment by kernel-io** [comment]
I'm really sorry about the whitespace being missing, I have no idea what is happening with GitHub at the moment. I will try edit later as it may just be a transient bug.

**Comment by treebee** [comment]
How exactly are you trying to pass the boolean?

`<Select>` does not have a separate `disabled` prop (like for example the `Button` component of `surface_bulma`, https://github.com/surface-ui/surface_bulma/blob/master/lib/surface_bulma/button.ex#L33),
but you can pass it in the `opts`:
```
<Select opts={{ disabled: true }} />
```

**Comment by Malian** [comment]
@kernel-io What do you mean by:

>passing a boolean value for the disabled attribute doesn't work as the HTML spec requires, and also not as it works in Phoenix.

According to https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes and the link to Phoenix documentation, the current behaviour is the expected behaviour.

"Repeating" the key as the value is not mandatory.

Could you explain what "does not work"?

**Comment by neilberkman** [comment]
See previous discussion [here](https://github.com/surface-ui/surface/issues/2#issuecomment-578140709)

**Comment by kernel-io** [comment]
okay, what doesn't work is the inbuilt Submit button (doesn't work in the sense that, if the value is true, then disabled will be added, but it doesn't seem to update when the value updates, I have confirmed the value changes by inspecting it next to the button), maybe I'm doing something wrong?

**Comment by treebee** [comment]
@kernel-io looks fine to me (except for `@changeset.valid?` probably having to be `not @changeset.valid?`) and I could reproduce the issue.

Looks like this isn't working since this change: https://github.com/surface-ui/surface/commit/0f7835d8d3ee973a2e384ff4cd8bdea9934d753c

I looked a bit into it and could confirm that the [attrs](https://github.com/surface-ui/surface/blob/master/lib/surface/components/form/submit.ex#L27) that are passed to the HTML `<button />` element actually change, but it doesn't have any effect on the generated HTML.

By playing around a bit more I noticed that it worked when using `:attrs={{ @opts }}`, while the computed `attrs` and `@opts` were exactly the same, so I assumed that it has to do something with `opts` being a property/assign?
When I made `attrs` a data property and computed it in an `update` function, everything worked.

Hope this helps experienced Surface devs to faster come up with the correct fix :)

**Comment by Malian** [comment]
@kernel-io I better understand the issue now, and I was able to reproduce it.
@treebee Thanks for investigating this issue.

Not sure why this happens... The `attrs` variable is updated, the directive handles the `:disabled`, ... @miguel-s as you reimplementend this component, do you have an idea?

**Comment by miguel-s** [comment]
@Malian I managed to reproduce it. Looks like this bug is not specific to the `Submit` component.

It seems to be related with declaring variables inside render. Maybe it disables change tracking? But that's not been an issue until now.

A quick fix would be to move everything inside the `~H`, like this:

```elixir
def render(assigns) do
  ~H"""
  <button type="submit" :attrs={{ (prop_to_attr_opts(assigns.class, :class) ++ assigns.opts ++ events_to_opts(assigns)) |> opts_to_attrs() }}><slot>{{ @label }}</slot></button>
  """
end
```

**Comment by Malian** [comment]
@miguel-s @msaraiva From the [doc](https://hexdocs.pm/phoenix_live_view/assigns-eex.html#liveeex-pitfalls)

> Never do anything on def render(assigns) besides rendering a template or invoking the ~L sigil

The proposed solution in the doc is to  explicitly precompute the assign in the LiveView, outside of render, but we cannot as the components are stateless. Another solution would be to extract this logic to a function and call it into `~H`

@miguel-s I managed to confirm that the quick fix you propose works.

**Comment by miguel-s** [comment]
@Malian Yep thought it would be related to that.

Strangely enough it works fine in some cases like this component [Reset](https://github.com/surface-ui/surface/blob/aec3daa8940fe045887a89cc4809a326034ffe94/lib/surface/components/form/reset.ex#L46), maybe because it relies on the Phoenix helpers instead of writing it's own html.

**Comment by Malian** [comment]
@miguel-s It maybe works because we call `@opts` inside the function, so LiveView know this part should be rerendered. I am not sure it will works if you extract the `@opts` to a variable, even with a function: `opts = assigns.opts`.

**Comment by miguel-s** [comment]
@Malian you're a genius 👏 I was able to verify your theory with my test case. I'll work on a fix asap.

**Comment by Malian** [comment]
@kernel-io Should be fixed in master, does it work for your use case?

**Comment by kernel-io** [comment]
Yup, can confirm working 👍🏿 

thanks guys!
