### ISSUE TITLE
Use x-bind:class from AlpineJS in custom component

### ISSUE THREAD

**Issue by jotaviobiondo** [surface-ui/surface#423]
Hi! First, I'm loving this lib, such an amazing work!

I'm using **Surface 0.4** with [AlpineJS](https://github.com/alpinejs/alpine) and I'm trying to use the `x-bind:class` from Alpine , but Surface emits the following warning:

![image](https://user-images.githubusercontent.com/7737375/120942591-5f6f7700-c700-11eb-968f-ac8249aa69a1.png)

An example: 

```html
<Link label="A Link" to="#" x-bind:class="{ 'show': showClass }" />
```

This binding using javascript (Alpine) to the `class` prop of a Surface component is possible?

**Comment by treebee** [comment]
@jotaviobiondo you can pass it as `opts`:

```
<Link label="A link" to="#" opts={{"x-bind:class": "{ 'show': showClass }" }} />
```

**Comment by msaraiva** [comment]
@jotaviobiondo just for further clarification, you can use `x-bind:class` or any other alpine directive directly in any HTML element, like:

```html
<div x-bind:class="{ 'show': showClass }" >
```

but you can't add them to components (like `<Link>`) because component's properties must be explicitly defined. The component's author is responsible for defining the public interface. Keep in mind that a component may render many HTML elements or none so we can't just forward any properties directly to a specific element.

**Comment by jotaviobiondo** [comment]
Hmm, got it! Thanks for the help and clarification guys 😄
