### ISSUE TITLE
Allow :if on slots

### ISSUE THREAD

**Issue by cschmatzler** [surface-ui/surface#457]
Hi!

A nice enhancement would be to allow `:if` on slots. 
For example, my page heading has an `actions` slot that is only shown conditionally and I'd like to be able to show that using
```
<:actions :if={@show_actions}>
...
</:actions>
```

This is important because the slot has conditional styling using `slot_assigned?`.

In addition, surrounding the `<:actions>` tag with `{#if}` crashes the page completely with `no function clause matching in Surface.Compiler.EExEngine.to_dynamic_nested_html/1`. This might be a separate issue, so if you want me to open one with full stacktrace please let me know.

**Comment by msaraiva** [comment]
Currently, slots cannot be defined dynamically because we need to generate their related code at compile-time, where we don't have access yet to any runtime info like assigns' values. This cannot be improved from our side and will only be possible if LV implements a standard API that accepts dynamic slots.
