### ISSUE TITLE
Improve documentation on Surface.Component vs Surface.LiveComponent for master branch

### ISSUE THREAD

**Issue by thorsten-de** [surface-ui/surface#489]
It would be great to emphasize the difference between `Surface.Component` and `Surface.LiveComponent` in the docs in more detail.

Documentation says: 
> Note: Stateless components cannot handle Phoenix LiveView events. If you need to handle them, please use a Surface.LiveComponent instead.

As I experienced, there's acutally more about this: Stateless components *don't handle any lifetime callbacks* like `mount/1` or `update/2`. This may be obvious when starting out now, but they *did handle them in the past*.

I migrated a LiveView app to Surface, and as data preprocessing inside the render callback is discouraged, there were some components using update for this task. These didn't have any event handling, so I thought going with `Surface.Component` is the key. There's no state management to be done, except data preparation for display. 

I used the published hex version until now and it worked perfectly well. Now I switched to the master branch, my components don't work anymore and I had a hard time figuring out the reason - it could be the bump to Phoenix 1.6.0-rc, or live_view 0.16 or something else. Just by chance I rememberd I read somewhere that `Surface.Component` used `Phoenix.LiveComponent` under the hood, and this changed in the master branch of surface. 

So I have rethink the usage of `mount` and `update` callbacks, and perhaps use a `LiveComponent` instead. This is perfectly fine, but that should be stated clearly somewhere.

**Comment by msaraiva** [comment]
Hi @thorsten-de!

Yes. The `mount` and `update` callbacks are no longer available as `Surface.Component` now is built on top of function components (instead of stateless live components). We'll review/update the docs and add a new "Migrating from v0.5.x to v0.6.x" section in our [Migration Guide](https://github.com/surface-ui/surface/blob/master/MIGRATING.md) as soon as `v0.6` is ready.

Basically, any data preparation that was done inside those callbacks must be moved to `render/1`. The API has been updated so you can use `assign`, `assign_new`, etc. in any function component. 

Here's an example from our tests where we adjusted the code: https://github.com/surface-ui/surface/commit/514bbbda4575378d45e3788a3f0391e8d0581a60#diff-13af13c1f87d799c73dbe03fb8f944c40bb68f6b4b14f7cdab105d160fe7fdddL108-R115

In the meantime, feel free to submit a PR to improve the docs or the website. Any help is certainly appreciated.

Cheers.
