### ISSUE TITLE
ErrorTag example for form

### ISSUE THREAD

**Issue by mxrguspxrt** [surface-ui/surface#525]
Good day!

https://surface-ui.org/builtincomponents/ErrorTag

```
<Form for={@changeset}>
  <Field name="email">
    <Label />
    <TextInput />
    <ErrorTag />
  </Field>
</Form>
```

Error tag does not work. When outputting form.errors, they always are empty list, altough @changeset has errors. Should the Form has parameter errors? Would it possible to have an example on documentation page?

Best regards!

**Comment by Malian** [comment]
Hi @mxrguspxrt !

Could you please provide a minimum project that reproduces the bug? I am not able to reproduce it.

Also, did you change the changeset action attribute? If no, you should do it.

Thanks!

**Comment by mxrguspxrt** [comment]
What is changeset action attribute?

**Comment by mxrguspxrt** [comment]
```
Map.merge(changeset, %{action: :insert})
```

Solved the issue, thank you @Malian ! :)

**Comment by Malian** [comment]
@mxrguspxrt good news!

For others who may come across this issue, the problem is not related to Surface, nor to PhoenixLiveView. It is a Phoenix HTML mechanism, which uses the `action` attribute of the changeset to decide whether or not to display the error.

See https://hexdocs.pm/ecto/Ecto.Changeset.html#module-changeset-actions for ore info:

> Frameworks such as Phoenix use the action value to define how HTML forms should act.

**Comment by joshuataylor** [comment]
Yeah, also got stuck on this again, you need to do this for your changeset:
```
    changeset = MyAwesomeSchema.changeset(%MyAwesomeSchema{}, data)
                |> Ecto.Changeset.apply_action(:insert)
```
