### ISSUE TITLE
Support HEEx as a templating language for use with Surface

### ISSUE THREAD

**Issue by zachallaun** [surface-ui/surface#669]
Hi there! To begin: Amazing work on Surface. I think that everyone can see that features first introduced in this project were a huge driving factor in some of the best latest enhancements to LiveView/`Phoenix.Component`. Now that LiveView's native HEEx templating has, in many ways, "caught up" to Surface templates, I was hoping to start a discussion about what it might look like for Surface to support HEEx as a templating language.

While I don't believe that `Phoenix.Component`'s equivalent features (attributes, for example) are quite at feature parity with Surface, the latest releases have certainly made it a bit more difficult to choose Surface over what is available by default -- from a templating perspective. However, Surface has introduced a handful of other features that are *extremely* useful:

* `LiveComponent` state management and event dispatching
* Contexts
* Colocated `*.hooks.js` files
* Scoped CSS

All of this makes me wonder whether it would be possible to abstract the choice of templating language from the "rest" of Surface, allowing people to choose a la carte which of these Surface enhancements they'd like to use without having to move "too far away" from the blessed path. I think this would lead to further adoption of Surface and would also help to provide a transition path for those looking to eventually move to Surface templates -- you can adopt Surface's organization to start and then rewrite/convert templates over time.

(Caveat: I know that the Surface compiler is a complex thing and I have no clue the degree to which Surface templates are "ingrained" in the features above (I know that some things like Scoped CSS complicate things).)

**Comment by msaraiva** [comment]
Hi @zachallaun!

Currently, you can use HEEx templates in Surface but each one of those features will not work or maybe work with limitations.

> * `LiveComponent` state management and event dispatching

The only difference here is that Surface dispatches to `@myself` by default, which was the original idea when LV came out but it was not possible back then due to LEEx limitations. That feature can only be implemented in HEEx itself and since that change would break a lot of the current projects, I don't see that happening any time soon.

> * Contexts

We could allow passing context values a HEEx component, however those values would not propagate to its children, unless again, we add support for that in HEEx itself.

> * Colocated `*.hooks.js` files

That could work without much effort.

> * Scoped CSS

This would require changes in HEEx too since it relies on adding extra information to HTML nodes in the tree.

So, unless LV wants to also implement all those features in the core, there's not much we can do about it.
